feat: add DA for fscloud
terraform-ibm-modules/terraform-ibm-event-streams pull request #181
Opened 2024-02-01 13:49 UTC by akocbek

### Description

### Release required?

- [ ] No release
- [ ] Patch release (`x.x.X`)
- [ ] Minor release (`x.X.x`)
- [ ] Major release (`X.x.x`)

##### Release notes content

### Run the pipeline

If the CI pipeline doesn't run when you create the PR, the PR requires a user with GitHub collaborators access to run the pipeline.

Run the CI pipeline when the PR is ready for review and you expect tests to pass. Add a comment to the PR with the following text:

```
/run pipeline
```

### Checklist for reviewers

- [ ] If relevant, a test for the change is included or updated with this PR.
- [ ] If relevant, documentation for the change is included or updated with this PR.

### For mergers

- Use a conventional commit message to set the release level. Follow the [guidelines](https://terraform-ibm-modules.github.io/documentation/#/merging.md).
- Include information that users need to know about the PR in the commit message. The commit message becomes part of the GitHub release notes.
- Use the **Squash and merge** option.

2024-02-01 16:30 UTC, akocbek commented
/run pipeline

2024-02-01 16:39 UTC, akocbek commented
/run pipeline

2024-02-06 10:26 UTC, akocbek commented
/run pipeline

2024-02-09 11:36 UTC, ocofaigh commented
There is a breaking change coming in https://github.com/terraform-ibm-modules/terraform-ibm-event-streams/pull/178 so going to merge that first

2024-02-13 10:24 UTC, ocofaigh commented
@akocbek Daniel PR is now merged, so you should be able to proceed now. Thanks

2024-02-15 10:54 UTC, akocbek commented
/run pipeline

2024-02-15 11:11 UTC, akocbek commented
/run pipeline

2024-02-15 11:51 UTC, akocbek commented
/run pipeline

2024-02-15 12:00 UTC, akocbek commented
/run pipeline

2024-02-15 13:14 UTC, akocbek commented
/run pipeline

2024-02-15 13:25 UTC, akocbek commented
/run pipeline

2024-02-15 13:33 UTC, akocbek commented
/run pipeline

2024-02-15 15:45 UTC, akocbek commented on solutions/fscloud/README.md
> +![da-fscloud](../../reference-architecture/da-fscloud.svg)
cloudant has the same and it works https://github.com/terraform-ibm-modules/terraform-ibm-cloudant/blob/main/solutions/dedicated/README.md?plain=1#L9

2024-02-16 15:54 UTC, ocofaigh commented on solutions/fscloud/version.tf
> +      version = "1.56.1"
Can you update this to 1.62.0 since its the latest and renovate will always use bump this to latest since its a DA

2024-02-16 15:54 UTC, ocofaigh requested changes
@akocbek just 1 comment and we should be good

2024-02-16 16:06 UTC, akocbek commented
/run pipeline

2024-02-16 18:03 UTC, ocofaigh approved these changes
Merging without a release for now, and will release when ibm_catalog.json is added

2024-02-16 18:03 UTC, merged

2024-02-17 04:12 UTC, terraform-ibm-modules-ops commented
:tada: This PR is included in version 2.0.1 :tada:

The release is available on [GitHub release](https://github.com/terraform-ibm-modules/terraform-ibm-event-streams/releases/tag/v2.0.1)

Your **[semantic-release](https://github.com/semantic-release/semantic-release)** bot :package::rocket: