ci: onboard event streams DA to catalog
terraform-ibm-modules/terraform-ibm-event-streams pull request #193
Opened 2024-02-22 14:22 UTC by akocbek

### Description

### Release required?

- [ ] No release
- [ ] Patch release (`x.x.X`)
- [ ] Minor release (`x.X.x`)
- [ ] Major release (`X.x.x`)

##### Release notes content

### Run the pipeline

If the CI pipeline doesn't run when you create the PR, the PR requires a user with GitHub collaborators access to run the pipeline.

Run the CI pipeline when the PR is ready for review and you expect tests to pass. Add a comment to the PR with the following text:

```
/run pipeline
```

### Checklist for reviewers

- [ ] If relevant, a test for the change is included or updated with this PR.
- [ ] If relevant, documentation for the change is included or updated with this PR.

### For mergers

- Use a conventional commit message to set the release level. Follow the [guidelines](https://terraform-ibm-modules.github.io/documentation/#/merging.md).
- Include information that users need to know about the PR in the commit message. The commit message becomes part of the GitHub release notes.
- Use the **Squash and merge** option.

2024-02-22 14:23 UTC, akocbek commented
/run pipeline

2024-02-22 21:18 UTC, ocofaigh commented on ibm_catalog.json
> +        "solution"
I recently found out that there is only a pre-defined set of tags that you can use. Please remove `event_streams` and `reference_architecture`. Please add `support_ibm` and `integration`

2024-02-22 21:19 UTC, ocofaigh commented
@SirSpidey would you mind reviewing the wording in the JSON please?

2024-02-22 22:08 UTC, SirSpidey requested changes
The features need more marketing fluff. Description should flesh-out the title.

2024-02-23 13:52 UTC, akocbek commented
/run pipeline

2024-02-23 13:58 UTC, akocbek commented
/run pipeline

2024-02-23 14:12 UTC, SirSpidey submitted a review, later dismissed
content for catalog details in `ibm_catalog.json` looks good.

2024-02-24 09:48 UTC, akocbek commented
/run pipeline

2024-02-26 10:12 UTC, akocbek commented
/run pipeline

2024-02-26 13:28 UTC, SirSpidey approved these changes
re-reviewed after rebase

2024-02-26 14:56 UTC, merged