Rewrite topics creation with for_each instead of count
terraform-ibm-modules/terraform-ibm-event-streams pull request #350
Opened 2024-12-03 03:20 UTC by navidsh

### Description

Rewrote the topic resource block to use `for_each` instead of `count` to allow adding or removing topics in the beginning or middle of the input topic list. Without this change, the topic resource block only relies on indexes when adding or removing topics. Addresses https://github.com/terraform-ibm-modules/terraform-ibm-event-streams/issues/349.

### Release required?

- [ ] No release
- [x] Patch release (`x.x.X`)
- [ ] Minor release (`x.X.x`)
- [ ] Major release (`X.x.x`)

##### Release notes content

Rewrote the topic resource block to use `for_each` instead of `count`. Using `for_each` provides more flexibility to add or remove topics in the beginning or middle of the input topic list.

### Run the pipeline

If the CI pipeline doesn't run when you create the PR, the PR requires a user with GitHub collaborators access to run the pipeline.

Run the CI pipeline when the PR is ready for review and you expect tests to pass. Add a comment to the PR with the following text:

```
/run pipeline
```

### Checklist for reviewers

- [ ] If relevant, a test for the change is included or updated with this PR.
- [ ] If relevant, documentation for the change is included or updated with this PR.

### For mergers

- Use a conventional commit message to set the release level. Follow the [guidelines](https://terraform-ibm-modules.github.io/documentation/#/merging.md).
- Include information that users need to know about the PR in the commit message. The commit message becomes part of the GitHub release notes.
- Use the **Squash and merge** option.

2024-12-03 03:20 UTC, navidsh commented
/run pipeline

2024-12-03 03:47 UTC, navidsh commented
I tested the following scenarios:
```hcl
topics = [
    {
      name       = "topic_10"
      partitions = 3
      config = {
        "cleanup.policy"  = "delete"
        "retention.ms"    = "86400000"
        "segment.bytes"   = "209715200"
        "retention.bytes" = "209715200"
      }
    },
    {
      name       = "topic_20"
      partitions = 3
      config = {
        "cleanup.policy"  = "delete"
        "retention.ms"    = "86400000"
        "segment.bytes"   = "209715200"
        "retention.bytes" = "209715200"
      }
    }
  ]
```

`terraform plan` output:
```
Terraform will perform the following actions:

  # module.event_streams.ibm_event_streams_topic.es_topic["topic_10"] will be created
  + resource "ibm_event_streams_topic" "es_topic" {
      + config               = {
          + "cleanup.policy"  = "delete"
          + "retention.bytes" = "209715200"
          + "retention.ms"    = "86400000"
          + "segment.bytes"   = "209715200"
        }
      + id                   = (known after apply)
      + kafka_brokers_sasl   = (known after apply)
      + kafka_http_url       = (known after apply)
      + name                 = "topic_10"
      + partitions           = 3
      + resource_instance_id = "crn:v1:bluemix:public:messagehub:us-south:a/26f737d77ed726547f77e08f865c5a26:4f645eda-a789-4408-a916-f9b25c04b8a3::"
    }

  # module.event_streams.ibm_event_streams_topic.es_topic["topic_20"] will be created
  + resource "ibm_event_streams_topic" "es_topic" {
      + config               = {
          + "cleanup.policy"  = "delete"
          + "retention.bytes" = "209715200"
          + "retention.ms"    = "86400000"
          + "segment.bytes"   = "209715200"
        }
      + id                   = (known after apply)
      + kafka_brokers_sasl   = (known after apply)
      + kafka_http_url       = (known after apply)
      + name                 = "topic_20"
      + partitions           = 3
      + resource_instance_id = "crn:v1:bluemix:public:messagehub:us-south:a/26f737d77ed726547f77e08f865c5a26:4f645eda-a789-4408-a916-f9b25c04b8a3::"
    }

Plan: 2 to add, 0 to change, 0 to destroy.
```

`terraform apply` output:
```
module.event_streams.ibm_event_streams_topic.es_topic["topic_20"]: Creating...
module.event_streams.ibm_event_streams_topic.es_topic["topic_10"]: Creating...
module.event_streams.ibm_event_streams_topic.es_topic["topic_20"]: Creation complete after 4s [id=crn:v1:bluemix:public:messagehub:us-south:a/26f737d77ed726547f77e08f865c5a26:4f645eda-a789-4408-a916-f9b25c04b8a3:topic:topic_20]
module.event_streams.ibm_event_streams_topic.es_topic["topic_10"]: Creation complete after 4s [id=crn:v1:bluemix:public:messagehub:us-south:a/26f737d77ed726547f77e08f865c5a26:4f645eda-a789-4408-a916-f9b25c04b8a3:topic:topic_10]
```

---

Adding a topic to the beginning of the list:
```hcl
topics = [
    {
      name       = "topic_0"
      partitions = 3
      config = {
        "cleanup.policy"  = "delete"
        "retention.ms"    = "86400000"
        "segment.bytes"   = "209715200"
        "retention.bytes" = "209715200"
      }
    },
    {
      name       = "topic_10"
      partitions = 3
      config = {
        "cleanup.policy"  = "delete"
        "retention.ms"    = "86400000"
        "segment.bytes"   = "209715200"
        "retention.bytes" = "209715200"
      }
    },
    {
      name       = "topic_20"
      partitions = 3
      config = {
        "cleanup.policy"  = "delete"
        "retention.ms"    = "86400000"
        "segment.bytes"   = "209715200"
        "retention.bytes" = "209715200"
      }
    }
  ]
```

`terraform plan` output:
```
Terraform will perform the following actions:

  # module.event_streams.ibm_event_streams_topic.es_topic["topic_0"] will be created
  + resource "ibm_event_streams_topic" "es_topic" {
      + config               = {
          + "cleanup.policy"  = "delete"
          + "retention.bytes" = "209715200"
          + "retention.ms"    = "86400000"
          + "segment.bytes"   = "209715200"
        }
      + id                   = (known after apply)
      + kafka_brokers_sasl   = (known after apply)
      + kafka_http_url       = (known after apply)
      + name                 = "topic_0"
      + partitions           = 3
      + resource_instance_id = "crn:v1:bluemix:public:messagehub:us-south:a/26f737d77ed726547f77e08f865c5a26:4f645eda-a789-4408-a916-f9b25c04b8a3::"
    }

Plan: 1 to add, 0 to change, 0 to destroy.
```

`terraform apply` output:
```
module.event_streams.ibm_event_streams_topic.es_topic["topic_0"]: Creating...
module.event_streams.ibm_event_streams_topic.es_topic["topic_0"]: Creation complete after 3s [id=crn:v1:bluemix:public:messagehub:us-south:a/26f737d77ed726547f77e08f865c5a26:4f645eda-a789-4408-a916-f9b25c04b8a3:topic:topic_0]
```

---

Adding a topic to the beginning of the list:
```hcl
topics = [
    {
      name       = "topic_0"
      partitions = 3
      config = {
        "cleanup.policy"  = "delete"
        "retention.ms"    = "86400000"
        "segment.bytes"   = "209715200"
        "retention.bytes" = "209715200"
      }
    },
    {
      name       = "topic_10"
      partitions = 3
      config = {
        "cleanup.policy"  = "delete"
        "retention.ms"    = "86400000"
        "segment.bytes"   = "209715200"
        "retention.bytes" = "209715200"
      }
    },
    {
      name       = "topic_20"
      partitions = 3
      config = {
        "cleanup.policy"  = "delete"
        "retention.ms"    = "86400000"
        "segment.bytes"   = "209715200"
        "retention.bytes" = "209715200"
      }
    }
  ]
```

`terraform plan` output:
```

```

`terraform apply` output:
```

```

---

Adding a topic to the beginning of the list:
```hcl
topics = [
    {
      name       = "topic_0"
      partitions = 3
      config = {
        "cleanup.policy"  = "delete"
        "retention.ms"    = "86400000"
        "segment.bytes"   = "209715200"
        "retention.bytes" = "209715200"
      }
    },
    {
      name       = "topic_10"
      partitions = 3
      config = {
        "cleanup.policy"  = "delete"
        "retention.ms"    = "86400000"
        "segment.bytes"   = "209715200"
        "retention.bytes" = "209715200"
      }
    },
    {
      name       = "topic_20"
      partitions = 3
      config = {
        "cleanup.policy"  = "delete"
        "retention.ms"    = "86400000"
        "segment.bytes"   = "209715200"
        "retention.bytes" = "209715200"
      }
    }
  ]
```

`terraform plan` output:
```

```

`terraform apply` output:
```

```

---

Adding a topic to the beginning of the list:
```hcl
topics = [
    {
      name       = "topic_0"
      partitions = 3
      config = {
        "cleanup.policy"  = "delete"
        "retention.ms"    = "86400000"
        "segment.bytes"   = "209715200"
        "retention.bytes" = "209715200"
      }
    },
    {
      name       = "topic_10"
      partitions = 3
      config = {
        "cleanup.policy"  = "delete"
        "retention.ms"    = "86400000"
        "segment.bytes"   = "209715200"
        "retention.bytes" = "209715200"
      }
    },
    {
      name       = "topic_20"
      partitions = 3
      config = {
        "cleanup.policy"  = "delete"
        "retention.ms"    = "86400000"
        "segment.bytes"   = "209715200"
        "retention.bytes" = "209715200"
      }
    }
  ]
```

`terraform plan` output:
```

```

`terraform apply` output:
```

```

---

Adding a topic to the beginning of the list:
```hcl
topics = [
    {
      name       = "topic_0"
      partitions = 3
      config = {
        "cleanup.policy"  = "delete"
        "retention.ms"    = "86400000"
        "segment.bytes"   = "209715200"
        "retention.bytes" = "209715200"
      }
    },
    {
      name       = "topic_10"
      partitions = 3
      config = {
        "cleanup.policy"  = "delete"
        "retention.ms"    = "86400000"
        "segment.bytes"   = "209715200"
        "retention.bytes" = "209715200"
      }
   [...]

2024-12-03 04:02 UTC, navidsh commented
I tested the following scenarios for removing topics.

---

Initial list of topics:

```hcl
topics = [
    {
      name       = "topic_0"
      partitions = 3
      config = {
        "cleanup.policy"  = "delete"
        "retention.ms"    = "86400000"
        "segment.bytes"   = "209715200"
        "retention.bytes" = "209715200"
      }
    },
    {
      name       = "topic_10"
      partitions = 3
      config = {
        "cleanup.policy"  = "delete"
        "retention.ms"    = "86400000"
        "segment.bytes"   = "209715200"
        "retention.bytes" = "209715200"
      }
    },
    {
      name       = "topic_15"
      partitions = 3
      config = {
        "cleanup.policy"  = "delete"
        "retention.ms"    = "86400000"
        "segment.bytes"   = "209715200"
        "retention.bytes" = "209715200"
      }
    },
    {
      name       = "topic_20"
      partitions = 3
      config = {
        "cleanup.policy"  = "delete"
        "retention.ms"    = "86400000"
        "segment.bytes"   = "209715200"
        "retention.bytes" = "209715200"
      }
    },
    {
      name       = "topic_25"
      partitions = 3
      config = {
        "cleanup.policy"  = "delete"
        "retention.ms"    = "86400000"
        "segment.bytes"   = "209715200"
        "retention.bytes" = "209715200"
      }
    }  ]
```

`terraform plan` output:
```
Terraform will perform the following actions:

  # module.event_streams.ibm_event_streams_topic.es_topic["topic_0"] will be created
  + resource "ibm_event_streams_topic" "es_topic" {
      + config               = {
          + "cleanup.policy"  = "delete"
          + "retention.bytes" = "209715200"
          + "retention.ms"    = "86400000"
          + "segment.bytes"   = "209715200"
        }
      + id                   = (known after apply)
      + kafka_brokers_sasl   = (known after apply)
      + kafka_http_url       = (known after apply)
      + name                 = "topic_0"
      + partitions           = 3
      + resource_instance_id = "crn:v1:bluemix:public:messagehub:us-south:a/26f737d77ed726547f77e08f865c5a26:4f645eda-a789-4408-a916-f9b25c04b8a3::"
    }

  # module.event_streams.ibm_event_streams_topic.es_topic["topic_10"] will be created
  + resource "ibm_event_streams_topic" "es_topic" {
      + config               = {
          + "cleanup.policy"  = "delete"
          + "retention.bytes" = "209715200"
          + "retention.ms"    = "86400000"
          + "segment.bytes"   = "209715200"
        }
      + id                   = (known after apply)
      + kafka_brokers_sasl   = (known after apply)
      + kafka_http_url       = (known after apply)
      + name                 = "topic_10"
      + partitions           = 3
      + resource_instance_id = "crn:v1:bluemix:public:messagehub:us-south:a/26f737d77ed726547f77e08f865c5a26:4f645eda-a789-4408-a916-f9b25c04b8a3::"
    }

  # module.event_streams.ibm_event_streams_topic.es_topic["topic_15"] will be created
  + resource "ibm_event_streams_topic" "es_topic" {
      + config               = {
          + "cleanup.policy"  = "delete"
          + "retention.bytes" = "209715200"
          + "retention.ms"    = "86400000"
          + "segment.bytes"   = "209715200"
        }
      + id                   = (known after apply)
      + kafka_brokers_sasl   = (known after apply)
      + kafka_http_url       = (known after apply)
      + name                 = "topic_15"
      + partitions           = 3
      + resource_instance_id = "crn:v1:bluemix:public:messagehub:us-south:a/26f737d77ed726547f77e08f865c5a26:4f645eda-a789-4408-a916-f9b25c04b8a3::"
    }

  # module.event_streams.ibm_event_streams_topic.es_topic["topic_20"] will be created
  + resource "ibm_event_streams_topic" "es_topic" {
      + config               = {
          + "cleanup.policy"  = "delete"
          + "retention.bytes" = "209715200"
          + "retention.ms"    = "86400000"
          + "segment.bytes"   = "209715200"
        }
      + id                   = (known after apply)
      + kafka_brokers_sasl   = (known after apply)
      + kafka_http_url       = (known after apply)
      + name                 = "topic_20"
      + partitions           = 3
      + resource_instance_id = "crn:v1:bluemix:public:messagehub:us-south:a/26f737d77ed726547f77e08f865c5a26:4f645eda-a789-4408-a916-f9b25c04b8a3::"
    }

  # module.event_streams.ibm_event_streams_topic.es_topic["topic_25"] will be created
  + resource "ibm_event_streams_topic" "es_topic" {
      + config               = {
          + "cleanup.policy"  = "delete"
          + "retention.bytes" = "209715200"
          + "retention.ms"    = "86400000"
          + "segment.bytes"   = "209715200"
        }
      + id                   = (known after apply)
      + kafka_brokers_sasl   = (known after apply)
      + kafka_http_url       = (known after apply)
      + name                 = "topic_25"
      + partitions           = 3
      + resource_instance_id = "crn:v1:bluemix:public:messagehub:us-south:a/26f737d77ed726547f77e08f865c5a26:4f645eda-a789-4408-a916-f9b25c04b8a3::"
    }

Plan: 5 to add, 0 to change, 0 to destroy.
```

`terraform apply` output:
```
module.event_streams.ibm_event_streams_topic.es_topic["topic_0"]: Creating...
module.event_streams.ibm_event_streams_topic.es_topic["topic_10"]: Creating...
module.event_streams.ibm_event_streams_topic.es_topic["topic_25"]: Creating...
module.event_streams.ibm_event_streams_topic.es_topic["topic_15"]: Creating...
module.event_streams.ibm_event_streams_topic.es_topic["topic_20"]: Creating...
module.event_streams.ibm_event_streams_topic.es_topic["topic_20"]: Creation complete after 2s [id=crn:v1:bluemix:public:messagehub:us-south:a/26f737d77ed726547f77e08f865c5a26:4f645eda-a789-4408-a916-f9b25c04b8a3:topic:topic_20]
module.event_streams.ibm_event_streams_topic.es_topic["topic_10"]: Creation complete after 2s [id=crn:v1:bluemix:public:messagehub:us-south:a/26f737d77ed726547f77e08f865c5a26:4f645eda-a789-4408-a916-f9b25c04b8a3:topic:topic_10]
module.event_streams.ibm_event_streams_topic.es_topic["topic_25"]: Creation complete after 3s [id=crn:v1:bluemix:public:messagehub:us-south:a/26f737d77ed726547f77e08f865c5a26:4f645eda-a789-4408-a916-f9b25c04b8a3:topic:topic_25]
module.event_streams.ibm_event_streams_topic.es_topic["topic_15"]: Creation complete after 3s [id=crn:v1:bluemix:public:messagehub:us-south:a/26f737d77ed726547f77e08f865c5a26:4f645eda-a789-4408-a916-f9b25c04b8a3:topic:topic_15]
module.event_streams.ibm_event_streams_topic.es_topic["topic_0"]: Creation complete after 3s [id=crn:v1:bluemix:public:messagehub:us-south:a/26f737d77ed726547f77e08f865c5a26:4f645eda-a789-4408-a916-f9b25c04b8a3:topic:topic_0]
```

---

Removing a topic from the beginning of the list:
```hcl
topics = [
    {
      name       = "topic_10"
      partitions = 3
      config = {
        "cleanup.policy"  = "delete"
        "retention.ms"    = "86400000"
        "segment.bytes"   = "209715200"
        "retention.bytes" = "209715200"
      }
    },
    {
      name       = "topic_15"
      partitions = 3
      config = {
        "cleanup.policy"  = "delete"
        "retention.ms"    = "86400000"
        "segment.bytes"   = "209715200"
        "retention.bytes" = "209715200"
      }
    },
    {
      name       = "topic_20"
      partitions = 3
      config = {
        "cleanup.policy"  = "delete"
        "retention.ms"    = "86400000"
        "segment.bytes"   = "209715200"
        "retention.bytes" = "209715200"
      }
    },
    {
      name       = "topic_25"
      partitions = 3
      config = {
        "cleanup.policy"  = "delete"
        "retention.ms"    = "86400000"
        "segment.bytes"   = "209715200"
        "retention.bytes" = "209715200"
      }
    }
  ]
```

`terraform plan` output:
```
Terraform will perform the following actions:

  # module.event_streams.ibm_event_streams_topic.es_topic["topic_0"] will be destroyed
  # (because key ["topic_0"] is not in for_each map)
  - resource "ib [...]

2024-12-03 12:31 UTC, ocofaigh commented
Thanks for the PR @navidsh - We have seen similar limitations before when using count. I'm interested to know what the impact is on current consumers though. I have a feeling terraform might want to recreate topics if a consumer has topics created already and then they try to upgrade to a new version of the module with the changes proposed in this PR.

The upgrade test in this repo will test this exact scenario, and I can see it is set up to run against the complete example, which will create 2 topics by default. So going to trigger the pipeline now to see how it reacts to the change..

2024-12-03 12:31 UTC, ocofaigh commented
/run pipeline

2024-12-03 15:18 UTC, navidsh commented
@ocofaigh the upgrade test did in fact fail!

2024-12-03 15:28 UTC, ocofaigh commented
Yes, so as I suspected moving from count to for_each is a breaking change:

```
TestRunUpgradeExample 2024-12-03T12:38:42Z command.go:185:   # module.event_streams.ibm_event_streams_topic.es_topic[0] will be destroyed
TestRunUpgradeExample 2024-12-03T12:38:42Z command.go:185:   # (because resource does not use count)
TestRunUpgradeExample 2024-12-03T12:38:42Z command.go:185:   - resource "ibm_event_streams_topic" "es_topic" {
TestRunUpgradeExample 2024-12-03T12:38:42Z command.go:185:       - config               = {
TestRunUpgradeExample 2024-12-03T12:38:42Z command.go:185:           - "cleanup.policy"  = "delete"
TestRunUpgradeExample 2024-12-03T12:38:42Z command.go:185:           - "retention.bytes" = "10485760"
TestRunUpgradeExample 2024-12-03T12:38:42Z command.go:185:           - "retention.ms"    = "86400000"
TestRunUpgradeExample 2024-12-03T12:38:42Z command.go:185:           - "segment.bytes"   = "10485760"
TestRunUpgradeExample 2024-12-03T12:38:42Z command.go:185:         } -> null
TestRunUpgradeExample 2024-12-03T12:38:42Z command.go:185:       - id                   = "crn:v1:bluemix:public:messagehub:us-south:a/abac0df06b644a9cabc6e44f55b3880e:eec19422-0196-4a55-9934-4199c3bdcead:topic:topic-1" -> null
TestRunUpgradeExample 2024-12-03T12:38:42Z command.go:185:       - kafka_brokers_sasl   = [
TestRunUpgradeExample 2024-12-03T12:38:42Z command.go:185:           - "broker-0-0k4wdmtl1j8p6r8h.kafka.svc03.us-south.eventstreams.cloud.ibm.com:9093",
TestRunUpgradeExample 2024-12-03T12:38:42Z command.go:185:           - "broker-1-0k4wdmtl1j8p6r8h.kafka.svc03.us-south.eventstreams.cloud.ibm.com:9093",
TestRunUpgradeExample 2024-12-03T12:38:42Z command.go:185:           - "broker-2-0k4wdmtl1j8p6r8h.kafka.svc03.us-south.eventstreams.cloud.ibm.com:9093",
TestRunUpgradeExample 2024-12-03T12:38:42Z command.go:185:           - "broker-3-0k4wdmtl1j8p6r8h.kafka.svc03.us-south.eventstreams.cloud.ibm.com:9093",
TestRunUpgradeExample 2024-12-03T12:38:42Z command.go:185:           - "broker-4-0k4wdmtl1j8p6r8h.kafka.svc03.us-south.eventstreams.cloud.ibm.com:9093",
TestRunUpgradeExample 2024-12-03T12:38:42Z command.go:185:           - "broker-5-0k4wdmtl1j8p6r8h.kafka.svc03.us-south.eventstreams.cloud.ibm.com:9093",
TestRunUpgradeExample 2024-12-03T12:38:42Z command.go:185:         ] -> null
TestRunUpgradeExample 2024-12-03T12:38:42Z command.go:185:       - kafka_http_url       = "https://0k4wdmtl1j8p6r8h.svc03.us-south.eventstreams.cloud.ibm.com" -> null
TestRunUpgradeExample 2024-12-03T12:38:42Z command.go:185:       - name                 = "topic-1" -> null
TestRunUpgradeExample 2024-12-03T12:38:42Z command.go:185:       - partitions           = 1 -> null
TestRunUpgradeExample 2024-12-03T12:38:42Z command.go:185:       - resource_instance_id = "crn:v1:bluemix:public:messagehub:us-south:a/abac0df06b644a9cabc6e44f55b3880e:eec19422-0196-4a55-9934-4199c3bdcead::" -> null
TestRunUpgradeExample 2024-12-03T12:38:42Z command.go:185:     }
TestRunUpgradeExample 2024-12-03T12:38:42Z command.go:185: 
TestRunUpgradeExample 2024-12-03T12:38:42Z command.go:185:   # module.event_streams.ibm_event_streams_topic.es_topic[1] will be destroyed
TestRunUpgradeExample 2024-12-03T12:38:42Z command.go:185:   # (because resource does not use count)
TestRunUpgradeExample 2024-12-03T12:38:42Z command.go:185:   - resource "ibm_event_streams_topic" "es_topic" {
TestRunUpgradeExample 2024-12-03T12:38:42Z command.go:185:       - config               = {
TestRunUpgradeExample 2024-12-03T12:38:42Z command.go:185:           - "cleanup.policy"  = "compact,delete"
TestRunUpgradeExample 2024-12-03T12:38:42Z command.go:185:           - "retention.bytes" = "1073741824"
TestRunUpgradeExample 2024-12-03T12:38:42Z command.go:185:           - "retention.ms"    = "86400000"
TestRunUpgradeExample 2024-12-03T12:38:42Z command.go:185:           - "segment.bytes"   = "5368[709](https://github.com/terraform-ibm-modules/terraform-ibm-event-streams/actions/runs/12139707831/job/33848113224#step:7:710)12"
TestRunUpgradeExample 2024-12-03T12:38:42Z command.go:185:         } -> null
TestRunUpgradeExample 2024-12-03T12:38:42Z command.go:185:       - id                   = "crn:v1:bluemix:public:messagehub:us-south:a/abac0df06b644a9cabc6e44f55b3880e:eec19422-0196-4a55-9934-4199c3bdcead:topic:topic-2" -> null
TestRunUpgradeExample 2024-12-03T12:38:42Z command.go:185:       - kafka_brokers_sasl   = [
TestRunUpgradeExample 2024-12-03T12:38:42Z command.go:185:           - "broker-0-0k4wdmtl1j8p6r8h.kafka.svc03.us-south.eventstreams.cloud.ibm.com:9093",
TestRunUpgradeExample 2024-12-03T12:38:42Z command.go:185:           - "broker-1-0k4wdmtl1j8p6r8h.kafka.svc03.us-south.eventstreams.cloud.ibm.com:9093",
TestRunUpgradeExample 2024-12-03T12:38:42Z command.go:185:           - "broker-2-0k4wdmtl1j8p6r8h.kafka.svc03.us-south.eventstreams.cloud.ibm.com:9093",
TestRunUpgradeExample 2024-12-03T12:38:42Z command.go:185:           - "broker-3-0k4wdmtl1j8p6r8h.kafka.svc03.us-south.eventstreams.cloud.ibm.com:9093",
TestRunUpgradeExample 2024-12-03T12:38:42Z command.go:185:           - "broker-4-0k4wdmtl1j8p6r8h.kafka.svc03.us-south.eventstreams.cloud.ibm.com:9093",
TestRunUpgradeExample 2024-12-03T12:38:42Z command.go:185:           - "broker-5-0k4wdmtl1j8p6r8h.kafka.svc03.us-south.eventstreams.cloud.ibm.com:9093",
TestRunUpgradeExample 2024-12-03T12:38:42Z command.go:185:         ] -> null
TestRunUpgradeExample 2024-12-03T12:38:42Z command.go:185:       - kafka_http_url       = "https://0k4wdmtl1j8p6r8h.svc03.us-south.eventstreams.cloud.ibm.com/" -> null
TestRunUpgradeExample 2024-12-03T12:38:42Z command.go:185:       - name                 = "topic-2" -> null
TestRunUpgradeExample 2024-12-03T12:38:42Z command.go:185:       - partitions           = 1 -> null
TestRunUpgradeExample 2024-12-03T12:38:42Z command.go:185:       - resource_instance_id = "crn:v1:bluemix:public:messagehub:us-south:a/abac0df06b644a9cabc6e44f55b3880e:eec19422-0196-4a55-9934-4199c3bdcead::" -> null
TestRunUpgradeExample 2024-12-03T12:38:42Z command.go:185:     }
TestRunUpgradeExample 2024-12-03T12:38:42Z command.go:185:
```

We may need to provide some guidance on how a user can prevent this. There might be some state moved commands that could be used (similar to [this](https://github.com/terraform-ibm-modules/terraform-ibm-landing-zone-vsi/releases/tag/v4.4.0))

2024-12-03 15:35 UTC, navidsh commented
@ocofaigh Is it possible to run the commands as part of unit tests?

2024-12-03 17:43 UTC, navidsh commented
Created topics using the latest released ES module:
```
> grep "terraform-ibm-event-streams" main.tf                                
  source            = "git::https://github.com/terraform-ibm-modules/terraform-ibm-event-streams.git?ref=v2.11.1"

> terraform init
Initializing the backend...
Initializing modules...
Initializing provider plugins...
- Reusing previous version of ibm-cloud/ibm from the dependency lock file
- Reusing previous version of hashicorp/time from the dependency lock file
- Using previously-installed ibm-cloud/ibm v1.72.0-beta0
- Using previously-installed hashicorp/time v0.12.1

Terraform has been successfully initialized!

You may now begin working with Terraform. Try running "terraform plan" to see
any changes that are required for your infrastructure. All Terraform commands
should now work.

If you ever set or change modules or backend configuration for Terraform,
rerun this command to reinitialize your working directory. If you forget, other
commands will detect it and remind you to do so if necessary.

> terraform plan
module.resource_group.data.ibm_resource_group.existing_resource_group[0]: Reading...
module.resource_group.data.ibm_resource_group.existing_resource_group[0]: Read complete after 1s [id=<redacted>]

Terraform used the selected providers to generate the following execution plan. Resource actions are indicated with the following symbols:
  + create

Terraform will perform the following actions:

  # module.event_streams.ibm_event_streams_topic.es_topic[0] will be created
  + resource "ibm_event_streams_topic" "es_topic" {
      + config               = {
          + "cleanup.policy"  = "delete"
          + "retention.bytes" = "10485760"
          + "retention.ms"    = "86400000"
          + "segment.bytes"   = "10485760"
        }
      + id                   = (known after apply)
      + kafka_brokers_sasl   = (known after apply)
      + kafka_http_url       = (known after apply)
      + name                 = "topic-1"
      + partitions           = 1
      + resource_instance_id = (known after apply)
    }

  # module.event_streams.ibm_event_streams_topic.es_topic[1] will be created
  + resource "ibm_event_streams_topic" "es_topic" {
      + config               = {
          + "cleanup.policy"  = "compact,delete"
          + "retention.bytes" = "1073741824"
          + "retention.ms"    = "86400000"
          + "segment.bytes"   = "536870912"
        }
      + id                   = (known after apply)
      + kafka_brokers_sasl   = (known after apply)
      + kafka_http_url       = (known after apply)
      + name                 = "topic-2"
      + partitions           = 1
      + resource_instance_id = (known after apply)
    }

  # module.event_streams.ibm_resource_instance.es_instance will be created
  + resource "ibm_resource_instance" "es_instance" {
      + account_id              = (known after apply)
      + allow_cleanup           = (known after apply)
      + created_at              = (known after apply)
      + created_by              = (known after apply)
      + crn                     = (known after apply)
      + dashboard_url           = (known after apply)
      + deleted_at              = (known after apply)
      + deleted_by              = (known after apply)
      + extensions              = (known after apply)
      + guid                    = (known after apply)
      + id                      = (known after apply)
      + last_operation          = (known after apply)
      + location                = "us-south"
      + locked                  = (known after apply)
      + name                    = "test-es"
      + onetime_credentials     = (known after apply)
      + plan                    = "standard"
      + plan_history            = (known after apply)
      + resource_aliases_url    = (known after apply)
      + resource_bindings_url   = (known after apply)
      + resource_controller_url = (known after apply)
      + resource_crn            = (known after apply)
      + resource_group_crn      = (known after apply)
      + resource_group_id       = "<redacted>"
      + resource_group_name     = (known after apply)
      + resource_id             = (known after apply)
      + resource_keys_url       = (known after apply)
      + resource_name           = (known after apply)
      + resource_plan_id        = (known after apply)
      + resource_status         = (known after apply)
      + restored_at             = (known after apply)
      + restored_by             = (known after apply)
      + scheduled_reclaim_at    = (known after apply)
      + scheduled_reclaim_by    = (known after apply)
      + service                 = "messagehub"
      + service_endpoints       = (known after apply)
      + state                   = (known after apply)
      + status                  = (known after apply)
      + sub_type                = (known after apply)
      + tags                    = (known after apply)
      + target_crn              = (known after apply)
      + type                    = (known after apply)
      + update_at               = (known after apply)
      + update_by               = (known after apply)

      + timeouts {
          + create = "3h"
          + delete = "15m"
          + update = "1h"
        }
    }

  # module.event_streams.time_sleep.wait_for_authorization_policy will be created
  + resource "time_sleep" "wait_for_authorization_policy" {
      + create_duration = "30s"
      + id              = (known after apply)
    }

Plan: 4 to add, 0 to change, 0 to destroy.

──────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────

Note: You didn't use the -out option to save this plan, so Terraform can't guarantee to take exactly these actions if you run "terraform apply" now.

> terraform apply -auto-approve
module.resource_group.data.ibm_resource_group.existing_resource_group[0]: Reading...
module.resource_group.data.ibm_resource_group.existing_resource_group[0]: Read complete after 1s [id=<redacted>]

Terraform used the selected providers to generate the following execution plan. Resource actions are indicated with the following symbols:
  + create

Terraform will perform the following actions:

  # module.event_streams.ibm_event_streams_topic.es_topic[0] will be created
  + resource "ibm_event_streams_topic" "es_topic" {
      + config               = {
          + "cleanup.policy"  = "delete"
          + "retention.bytes" = "10485760"
          + "retention.ms"    = "86400000"
          + "segment.bytes"   = "10485760"
        }
      + id                   = (known after apply)
      + kafka_brokers_sasl   = (known after apply)
      + kafka_http_url       = (known after apply)
      + name                 = "topic-1"
      + partitions           = 1
      + resource_instance_id = (known after apply)
    }

  # module.event_streams.ibm_event_streams_topic.es_topic[1] will be created
  + resource "ibm_event_streams_topic" "es_topic" {
      + config               = {
          + "cleanup.policy"  = "compact,delete"
          + "retention.bytes" = "1073741824"
          + "retention.ms"    = "86400000"
          + "segment.bytes"   = "536870912"
        }
      + id                   = (known after apply)
      + kafka_brokers_sasl   = (known after apply)
      + kafka_http_url       = (known after apply)
      + name                 = "topic-2"
      + partitions           = 1
      + resource_instance_id = (known after apply)
    }

  # module.event_streams.ibm_resource_instance.es_instance will be created
  + resource "ibm_resource_instance" "es_instance" {
      + account_id              = (known after apply)
      + allow_cleanup           = (known after apply)
      + created_at              = (known after apply)
      + created_by              = (known after apply)
      + crn                     = (known after apply)
      + dashboard_url            [...]

2024-12-03 20:33 UTC, navidsh commented
Schematics plan prior to `move` command:
```
 
 2024/12/03 20:17:04 [1m-----  Terraform PLAN  -----[21m[0m
 
 2024/12/03 20:17:04 [34mStarting command: terraform1.6 plan -input=false -refresh=true -state=terraform.tfstate -var-file=schematics.tfvars -no-color -out=tfplan.binary[39m[0m
 2024/12/03 20:17:04 Starting command: terraform1.6 plan -input=false -refresh=true -state=terraform.tfstate -var-file=schematics.tfvars -no-color -out=tfplan.binary
 2024/12/03 20:17:11 Terraform plan | module.resource_group.data.ibm_resource_group.existing_resource_group[0]: Reading...
 2024/12/03 20:17:12 Terraform plan | module.resource_group.data.ibm_resource_group.existing_resource_group[0]: Read complete after 0s [id=19dd055f15844a0ca5b8212a143fc5d1]
 2024/12/03 20:17:12 Terraform plan | module.event_streams.time_sleep.wait_for_authorization_policy: Refreshing state... [id=2024-12-03T18:45:18Z]
 2024/12/03 20:17:12 Terraform plan | module.event_streams.ibm_resource_instance.es_instance: Refreshing state... [id=crn:v1:bluemix:public:messagehub:us-south:a/26f737d77ed726547f77e08f865c5a26:a6d13218-17bc-43e7-b3aa-125fc7608fd0::]
 2024/12/03 20:17:13 Terraform plan | module.event_streams.ibm_event_streams_topic.es_topic[1]: Refreshing state... [id=crn:v1:bluemix:public:messagehub:us-south:a/26f737d77ed726547f77e08f865c5a26:a6d13218-17bc-43e7-b3aa-125fc7608fd0:topic:topic_20]
 2024/12/03 20:17:13 Terraform plan | module.event_streams.ibm_event_streams_topic.es_topic[0]: Refreshing state... [id=crn:v1:bluemix:public:messagehub:us-south:a/26f737d77ed726547f77e08f865c5a26:a6d13218-17bc-43e7-b3aa-125fc7608fd0:topic:topic_10]
 2024/12/03 20:17:13 Terraform plan | module.event_streams.ibm_resource_key.service_credentials["es_writer"]: Refreshing state... [id=crn:v1:bluemix:public:messagehub:us-south:a/26f737d77ed726547f77e08f865c5a26:a6d13218-17bc-43e7-b3aa-125fc7608fd0:resource-key:468aafe6-854f-498b-85a1-6b2c1c49b366]
 2024/12/03 20:17:13 Terraform plan | module.event_streams.ibm_resource_key.service_credentials["es_reader"]: Refreshing state... [id=crn:v1:bluemix:public:messagehub:us-south:a/26f737d77ed726547f77e08f865c5a26:a6d13218-17bc-43e7-b3aa-125fc7608fd0:resource-key:5c7cf910-455a-40eb-a69b-bfea058a60ce]
 2024/12/03 20:17:13 Terraform plan | module.event_streams.ibm_resource_key.service_credentials["es_manager"]: Refreshing state... [id=crn:v1:bluemix:public:messagehub:us-south:a/26f737d77ed726547f77e08f865c5a26:a6d13218-17bc-43e7-b3aa-125fc7608fd0:resource-key:d319e00d-2832-4fcb-b989-5f035d4947d0]
 2024/12/03 20:17:19 Terraform plan | 
 2024/12/03 20:17:19 Terraform plan | Terraform used the selected providers to generate the following execution
 2024/12/03 20:17:19 Terraform plan | plan. Resource actions are indicated with the following symbols:
 2024/12/03 20:17:19 Terraform plan |   + create
 2024/12/03 20:17:19 Terraform plan |   - destroy
 2024/12/03 20:17:19 Terraform plan | 
 2024/12/03 20:17:19 Terraform plan | Terraform will perform the following actions:
 2024/12/03 20:17:19 Terraform plan | 
 2024/12/03 20:17:19 Terraform plan |   # module.event_streams.ibm_event_streams_topic.es_topic[0] will be destroyed
 2024/12/03 20:17:19 Terraform plan |   # (because resource does not use count)
 2024/12/03 20:17:19 Terraform plan |   - resource "ibm_event_streams_topic" "es_topic" {
 2024/12/03 20:17:19 Terraform plan |       - config               = {
 2024/12/03 20:17:19 Terraform plan |           - "cleanup.policy"  = "delete"
 2024/12/03 20:17:19 Terraform plan |           - "retention.bytes" = "209715200"
 2024/12/03 20:17:19 Terraform plan |           - "retention.ms"    = "86400000"
 2024/12/03 20:17:19 Terraform plan |           - "segment.bytes"   = "209715200"
 2024/12/03 20:17:19 Terraform plan |         } -> null
 2024/12/03 20:17:19 Terraform plan |       - id                   = "crn:v1:bluemix:public:messagehub:us-south:a/26f737d77ed726547f77e08f865c5a26:a6d13218-17bc-43e7-b3aa-125fc7608fd0:topic:topic_10" -> null
 2024/12/03 20:17:19 Terraform plan |       - kafka_brokers_sasl   = [
 2024/12/03 20:17:19 Terraform plan |           - "broker-0-8k2w6nm9z9299rnk.kafka.svc03.us-south.eventstreams.cloud.ibm.com:9093",
 2024/12/03 20:17:19 Terraform plan |           - "broker-1-8k2w6nm9z9299rnk.kafka.svc03.us-south.eventstreams.cloud.ibm.com:9093",
 2024/12/03 20:17:19 Terraform plan |           - "broker-2-8k2w6nm9z9299rnk.kafka.svc03.us-south.eventstreams.cloud.ibm.com:9093",
 2024/12/03 20:17:19 Terraform plan |           - "broker-3-8k2w6nm9z9299rnk.kafka.svc03.us-south.eventstreams.cloud.ibm.com:9093",
 2024/12/03 20:17:19 Terraform plan |           - "broker-4-8k2w6nm9z9299rnk.kafka.svc03.us-south.eventstreams.cloud.ibm.com:9093",
 2024/12/03 20:17:19 Terraform plan |           - "broker-5-8k2w6nm9z9299rnk.kafka.svc03.us-south.eventstreams.cloud.ibm.com:9093",
 2024/12/03 20:17:19 Terraform plan |         ] -> null
 2024/12/03 20:17:19 Terraform plan |       - kafka_http_url       = "https://8k2w6nm9z9299rnk.svc03.us-south.eventstreams.cloud.ibm.com" -> null
 2024/12/03 20:17:19 Terraform plan |       - name                 = "topic_10" -> null
 2024/12/03 20:17:19 Terraform plan |       - partitions           = 3 -> null
 2024/12/03 20:17:19 Terraform plan |       - resource_instance_id = "crn:v1:bluemix:public:messagehub:us-south:a/26f737d77ed726547f77e08f865c5a26:a6d13218-17bc-43e7-b3aa-125fc7608fd0::" -> null
 2024/12/03 20:17:19 Terraform plan |     }
 2024/12/03 20:17:19 Terraform plan | 
 2024/12/03 20:17:19 Terraform plan |   # module.event_streams.ibm_event_streams_topic.es_topic[1] will be destroyed
 2024/12/03 20:17:19 Terraform plan |   # (because resource does not use count)
 2024/12/03 20:17:19 Terraform plan |   - resource "ibm_event_streams_topic" "es_topic" {
 2024/12/03 20:17:19 Terraform plan |       - config               = {
 2024/12/03 20:17:19 Terraform plan |           - "cleanup.policy"  = "delete"
 2024/12/03 20:17:19 Terraform plan |           - "retention.bytes" = "209715200"
 2024/12/03 20:17:19 Terraform plan |           - "retention.ms"    = "86400000"
 2024/12/03 20:17:19 Terraform plan |           - "segment.bytes"   = "209715200"
 2024/12/03 20:17:19 Terraform plan |         } -> null
 2024/12/03 20:17:19 Terraform plan |       - id                   = "crn:v1:bluemix:public:messagehub:us-south:a/26f737d77ed726547f77e08f865c5a26:a6d13218-17bc-43e7-b3aa-125fc7608fd0:topic:topic_20" -> null
 2024/12/03 20:17:19 Terraform plan |       - kafka_brokers_sasl   = [
 2024/12/03 20:17:19 Terraform plan |           - "broker-0-8k2w6nm9z9299rnk.kafka.svc03.us-south.eventstreams.cloud.ibm.com:9093",
 2024/12/03 20:17:19 Terraform plan |           - "broker-1-8k2w6nm9z9299rnk.kafka.svc03.us-south.eventstreams.cloud.ibm.com:9093",
 2024/12/03 20:17:19 Terraform plan |           - "broker-2-8k2w6nm9z9299rnk.kafka.svc03.us-south.eventstreams.cloud.ibm.com:9093",
 2024/12/03 20:17:19 Terraform plan |           - "broker-3-8k2w6nm9z9299rnk.kafka.svc03.us-south.eventstreams.cloud.ibm.com:9093",
 2024/12/03 20:17:19 Terraform plan |           - "broker-4-8k2w6nm9z9299rnk.kafka.svc03.us-south.eventstreams.cloud.ibm.com:9093",
 2024/12/03 20:17:19 Terraform plan |           - "broker-5-8k2w6nm9z9299rnk.kafka.svc03.us-south.eventstreams.cloud.ibm.com:9093",
 2024/12/03 20:17:19 Terraform plan |         ] -> null
 2024/12/03 20:17:19 Terraform plan |       - kafka_http_url       = "https://8k2w6nm9z9299rnk.svc03.us-south.eventstreams.cloud.ibm.com" -> null
 2024/12/03 20:17:19 Terraform plan |       - name                 = "topic_20" -> null
 2024/12/03 20:17:19 Terraform plan |       - partitions           = 3 -> null
 2024/12/03 20:17:19 Terraform plan |       - resource_instance_id = "crn:v1:bluemix:public:messagehub:us-south:a/26f737d77ed726547f77e08f865c5a26:a6d13218-17bc-43e7-b3aa-125fc7608fd0::" -> null
 2024/12/03 20:17:19 Terraform plan |     }
 2024/12/03 20:17:19 Terraform plan | 
 2024/12/03 20:17:19 Terraform plan |   [...]

2024-12-05 10:25 UTC, ocofaigh commented
/run pipeline

2024-12-05 10:25 UTC, ocofaigh approved these changes

2024-12-05 10:32 UTC, ocofaigh commented
@navidsh Since this is a breaking change, the next release will be a major version update. But that got me thinking, should we also make the fix for `quotas` and `cbr_rules` at the same time so we don’t have further breaking change releases?

2024-12-06 12:23 UTC, ocofaigh requested changes
As discussed internally, lets make the same change for `quotas` to avoid having to do another breaking change. No need to change CBRs, as you can only actually create 1 CBR rule (with multiple contexts) per service instance

2024-12-09 03:27 UTC, navidsh commented
Existing quotas:
```
> export TF_VAR_quotas='[{"entity"= "iam-ServiceId-00000000-1111-0000-0000-000000000000","producer_byte_rate" = 100000,"consumer_byte_rate" = 200000},{"entity"= "iam-ServiceId-00000000-2222-0000-0000-000000000000","producer_byte_rate" = 100000,"consumer_byte_rate" = 200000}]'
```

Upgrade scenario (adding a new quota to be beginning of the quotas list):
```
> export TF_VAR_quotas='[{"entity"= "iam-ServiceId-00000000-0000-0000-0000-000000000000","producer_byte_rate" = 100000,"consumer_byte_rate" = 200000},{"entity"= "iam-ServiceId-00000000-1111-0000-0000-000000000000","producer_byte_rate" = 100000,"consumer_byte_rate" = 200000},{"entity"= "iam-ServiceId-00000000-2222-0000-0000-000000000000","producer_byte_rate" = 100000,"consumer_byte_rate" = 200000}]'

> terraform plan
time_sleep.wait_for_authorization_policy: Refreshing state... [id=2024-12-06T03:20:24Z]
ibm_resource_instance.es_instance: Refreshing state... [id=crn:v1:bluemix:public:messagehub:us-east:a/26f737d77ed726547f77e08f865c5a26:d70fb8a6-bd12-4d60-b813-5e7654077f2b::]
ibm_event_streams_quota.eventstreams_quotas[1]: Refreshing state... [id=crn:v1:bluemix:public:messagehub:us-east:a/26f737d77ed726547f77e08f865c5a26:d70fb8a6-bd12-4d60-b813-5e7654077f2b:quota:iam-ServiceId-00000000-2222-0000-0000-000000000000]
ibm_event_streams_quota.eventstreams_quotas[0]: Refreshing state... [id=crn:v1:bluemix:public:messagehub:us-east:a/26f737d77ed726547f77e08f865c5a26:d70fb8a6-bd12-4d60-b813-5e7654077f2b:quota:iam-ServiceId-00000000-1111-0000-0000-000000000000]

Terraform used the selected providers to generate the following execution plan. Resource actions are indicated with the following symbols:
  + create
  - destroy

Terraform will perform the following actions:

  # ibm_event_streams_quota.eventstreams_quotas[0] will be destroyed
  # (because resource does not use count)
  - resource "ibm_event_streams_quota" "eventstreams_quotas" {
      - consumer_byte_rate   = 200000 -> null
      - entity               = "iam-ServiceId-00000000-1111-0000-0000-000000000000" -> null
      - id                   = "crn:v1:bluemix:public:messagehub:us-east:a/26f737d77ed726547f77e08f865c5a26:d70fb8a6-bd12-4d60-b813-5e7654077f2b:quota:iam-ServiceId-00000000-1111-0000-0000-000000000000" -> null
      - producer_byte_rate   = 100000 -> null
      - resource_instance_id = "crn:v1:bluemix:public:messagehub:us-east:a/26f737d77ed726547f77e08f865c5a26:d70fb8a6-bd12-4d60-b813-5e7654077f2b::" -> null
    }

  # ibm_event_streams_quota.eventstreams_quotas[1] will be destroyed
  # (because resource does not use count)
  - resource "ibm_event_streams_quota" "eventstreams_quotas" {
      - consumer_byte_rate   = 200000 -> null
      - entity               = "iam-ServiceId-00000000-2222-0000-0000-000000000000" -> null
      - id                   = "crn:v1:bluemix:public:messagehub:us-east:a/26f737d77ed726547f77e08f865c5a26:d70fb8a6-bd12-4d60-b813-5e7654077f2b:quota:iam-ServiceId-00000000-2222-0000-0000-000000000000" -> null
      - producer_byte_rate   = 100000 -> null
      - resource_instance_id = "crn:v1:bluemix:public:messagehub:us-east:a/26f737d77ed726547f77e08f865c5a26:d70fb8a6-bd12-4d60-b813-5e7654077f2b::" -> null
    }

  # ibm_event_streams_quota.eventstreams_quotas["iam-ServiceId-00000000-0000-0000-0000-000000000000"] will be created
  + resource "ibm_event_streams_quota" "eventstreams_quotas" {
      + consumer_byte_rate   = 200000
      + entity               = "iam-ServiceId-00000000-0000-0000-0000-000000000000"
      + id                   = (known after apply)
      + producer_byte_rate   = 100000
      + resource_instance_id = "crn:v1:bluemix:public:messagehub:us-east:a/26f737d77ed726547f77e08f865c5a26:d70fb8a6-bd12-4d60-b813-5e7654077f2b::"
    }

  # ibm_event_streams_quota.eventstreams_quotas["iam-ServiceId-00000000-1111-0000-0000-000000000000"] will be created
  + resource "ibm_event_streams_quota" "eventstreams_quotas" {
      + consumer_byte_rate   = 200000
      + entity               = "iam-ServiceId-00000000-1111-0000-0000-000000000000"
      + id                   = (known after apply)
      + producer_byte_rate   = 100000
      + resource_instance_id = "crn:v1:bluemix:public:messagehub:us-east:a/26f737d77ed726547f77e08f865c5a26:d70fb8a6-bd12-4d60-b813-5e7654077f2b::"
    }

  # ibm_event_streams_quota.eventstreams_quotas["iam-ServiceId-00000000-2222-0000-0000-000000000000"] will be created
  + resource "ibm_event_streams_quota" "eventstreams_quotas" {
      + consumer_byte_rate   = 200000
      + entity               = "iam-ServiceId-00000000-2222-0000-0000-000000000000"
      + id                   = (known after apply)
      + producer_byte_rate   = 100000
      + resource_instance_id = "crn:v1:bluemix:public:messagehub:us-east:a/26f737d77ed726547f77e08f865c5a26:d70fb8a6-bd12-4d60-b813-5e7654077f2b::"
    }

Plan: 3 to add, 0 to change, 2 to destroy.

─────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────

Note: You didn't use the -out option to save this plan, so Terraform can't guarantee to take exactly these actions if you run "terraform apply" now.

```

Terraform move:
```
> terraform state mv "ibm_event_streams_quota.eventstreams_quotas[0]" 'ibm_event_streams_quota.eventstreams_quotas["iam-ServiceId-00000000-1111-0000-0000-000000000000"]'
Move "ibm_event_streams_quota.eventstreams_quotas[0]" to "ibm_event_streams_quota.eventstreams_quotas[\"iam-ServiceId-00000000-1111-0000-0000-000000000000\"]"
Successfully moved 1 object(s).

> terraform state mv "ibm_event_streams_quota.eventstreams_quotas[1]" 'ibm_event_streams_quota.eventstreams_quotas["iam-ServiceId-00000000-2222-0000-0000-000000000000"]'
Move "ibm_event_streams_quota.eventstreams_quotas[1]" to "ibm_event_streams_quota.eventstreams_quotas[\"iam-ServiceId-00000000-2222-0000-0000-000000000000\"]"
Successfully moved 1 object(s).
```

Terraform plan:
```
> terraform plan                                                                                                                                                         
time_sleep.wait_for_authorization_policy: Refreshing state... [id=2024-12-06T03:20:24Z]
ibm_resource_instance.es_instance: Refreshing state... [id=crn:v1:bluemix:public:messagehub:us-east:a/26f737d77ed726547f77e08f865c5a26:d70fb8a6-bd12-4d60-b813-5e7654077f2b::]
ibm_event_streams_quota.eventstreams_quotas["iam-ServiceId-00000000-1111-0000-0000-000000000000"]: Refreshing state... [id=crn:v1:bluemix:public:messagehub:us-east:a/26f737d77ed726547f77e08f865c5a26:d70fb8a6-bd12-4d60-b813-5e7654077f2b:quota:iam-ServiceId-00000000-1111-0000-0000-000000000000]
ibm_event_streams_quota.eventstreams_quotas["iam-ServiceId-00000000-2222-0000-0000-000000000000"]: Refreshing state... [id=crn:v1:bluemix:public:messagehub:us-east:a/26f737d77ed726547f77e08f865c5a26:d70fb8a6-bd12-4d60-b813-5e7654077f2b:quota:iam-ServiceId-00000000-2222-0000-0000-000000000000]

Terraform used the selected providers to generate the following execution plan. Resource actions are indicated with the following symbols:
  + create

Terraform will perform the following actions:

  # ibm_event_streams_quota.eventstreams_quotas["iam-ServiceId-00000000-0000-0000-0000-000000000000"] will be created
  + resource "ibm_event_streams_quota" "eventstreams_quotas" {
      + consumer_byte_rate   = 200000
      + entity               = "iam-ServiceId-00000000-0000-0000-0000-000000000000"
      + id                   = (known after apply)
      + producer_byte_rate   = 100000
      + resource_instance_id = "crn:v1:bluemix:public:messagehub:us-east:a/26f737d77ed726547f77e08f865c5a26:d70fb8a6-bd12-4d60-b813-5e7654077f2b::"
    }

Plan: 1 to add, 0 to change, 0 to destroy.

───────────────────────────────────────────────────────────────────────────────────────────────────── [...]

2024-12-09 05:00 UTC, navidsh commented
Testing Schematics upgrade scenario for quotas:

---

Initial quotas value:
```
quotas='[{"entity"= "iam-ServiceId-00000000-1111-0000-0000-000000000000","producer_byte_rate" = 100000,"consumer_byte_rate" = 200000},{"entity"= "iam-ServiceId-00000000-2222-0000-0000-000000000000","producer_byte_rate" = 100000,"consumer_byte_rate" = 200000}]'
```

Upgrading & Adding a quota to the list:
```
quotas='[{"entity"= "iam-ServiceId-00000000-0000-0000-0000-000000000000","producer_byte_rate" = 100000,"consumer_byte_rate" = 200000},{"entity"= "iam-ServiceId-00000000-1111-0000-0000-000000000000","producer_byte_rate" = 100000,"consumer_byte_rate" = 200000},{"entity"= "iam-ServiceId-00000000-2222-0000-0000-000000000000","producer_byte_rate" = 100000,"consumer_byte_rate" = 200000}]'
```

Output of Schematics plan:
```
2024/12/09 04:33:18 Terraform plan | 
 2024/12/09 04:33:18 Terraform plan | Terraform used the selected providers to generate the following execution
 2024/12/09 04:33:18 Terraform plan | plan. Resource actions are indicated with the following symbols:
 2024/12/09 04:33:18 Terraform plan |   + create
 2024/12/09 04:33:18 Terraform plan |   - destroy
 2024/12/09 04:33:18 Terraform plan | 
 2024/12/09 04:33:18 Terraform plan | Terraform will perform the following actions:
 2024/12/09 04:33:18 Terraform plan | 
 2024/12/09 04:33:18 Terraform plan |   # ibm_event_streams_quota.eventstreams_quotas[0] will be destroyed
 2024/12/09 04:33:18 Terraform plan |   # (because resource does not use count)
 2024/12/09 04:33:18 Terraform plan |   - resource "ibm_event_streams_quota" "eventstreams_quotas" {
 2024/12/09 04:33:18 Terraform plan |       - consumer_byte_rate   = 200000 -> null
 2024/12/09 04:33:18 Terraform plan |       - entity               = "iam-ServiceId-00000000-1111-0000-0000-000000000000" -> null
 2024/12/09 04:33:18 Terraform plan |       - id                   = "crn:v1:bluemix:public:messagehub:us-south:a/26f737d77ed726547f77e08f865c5a26:794b9f0c-535e-4860-b317-4e0a70323a22:quota:iam-ServiceId-00000000-1111-0000-0000-000000000000" -> null
 2024/12/09 04:33:18 Terraform plan |       - producer_byte_rate   = 100000 -> null
 2024/12/09 04:33:18 Terraform plan |       - resource_instance_id = "crn:v1:bluemix:public:messagehub:us-south:a/26f737d77ed726547f77e08f865c5a26:794b9f0c-535e-4860-b317-4e0a70323a22::" -> null
 2024/12/09 04:33:18 Terraform plan |     }
 2024/12/09 04:33:18 Terraform plan | 
 2024/12/09 04:33:18 Terraform plan |   # ibm_event_streams_quota.eventstreams_quotas[1] will be destroyed
 2024/12/09 04:33:18 Terraform plan |   # (because resource does not use count)
 2024/12/09 04:33:18 Terraform plan |   - resource "ibm_event_streams_quota" "eventstreams_quotas" {
 2024/12/09 04:33:18 Terraform plan |       - consumer_byte_rate   = 200000 -> null
 2024/12/09 04:33:18 Terraform plan |       - entity               = "iam-ServiceId-00000000-2222-0000-0000-000000000000" -> null
 2024/12/09 04:33:18 Terraform plan |       - id                   = "crn:v1:bluemix:public:messagehub:us-south:a/26f737d77ed726547f77e08f865c5a26:794b9f0c-535e-4860-b317-4e0a70323a22:quota:iam-ServiceId-00000000-2222-0000-0000-000000000000" -> null
 2024/12/09 04:33:18 Terraform plan |       - producer_byte_rate   = 100000 -> null
 2024/12/09 04:33:18 Terraform plan |       - resource_instance_id = "crn:v1:bluemix:public:messagehub:us-south:a/26f737d77ed726547f77e08f865c5a26:794b9f0c-535e-4860-b317-4e0a70323a22::" -> null
 2024/12/09 04:33:18 Terraform plan |     }
 2024/12/09 04:33:18 Terraform plan | 
 2024/12/09 04:33:18 Terraform plan |   # ibm_event_streams_quota.eventstreams_quotas["iam-ServiceId-00000000-0000-0000-0000-000000000000"] will be created
 2024/12/09 04:33:18 Terraform plan |   + resource "ibm_event_streams_quota" "eventstreams_quotas" {
 2024/12/09 04:33:18 Terraform plan |       + consumer_byte_rate   = 200000
 2024/12/09 04:33:18 Terraform plan |       + entity               = "iam-ServiceId-00000000-0000-0000-0000-000000000000"
 2024/12/09 04:33:18 Terraform plan |       + id                   = (known after apply)
 2024/12/09 04:33:18 Terraform plan |       + producer_byte_rate   = 100000
 2024/12/09 04:33:18 Terraform plan |       + resource_instance_id = "crn:v1:bluemix:public:messagehub:us-south:a/26f737d77ed726547f77e08f865c5a26:794b9f0c-535e-4860-b317-4e0a70323a22::"
 2024/12/09 04:33:18 Terraform plan |     }
 2024/12/09 04:33:18 Terraform plan | 
 2024/12/09 04:33:18 Terraform plan |   # ibm_event_streams_quota.eventstreams_quotas["iam-ServiceId-00000000-1111-0000-0000-000000000000"] will be created
 2024/12/09 04:33:18 Terraform plan |   + resource "ibm_event_streams_quota" "eventstreams_quotas" {
 2024/12/09 04:33:18 Terraform plan |       + consumer_byte_rate   = 200000
 2024/12/09 04:33:18 Terraform plan |       + entity               = "iam-ServiceId-00000000-1111-0000-0000-000000000000"
 2024/12/09 04:33:18 Terraform plan |       + id                   = (known after apply)
 2024/12/09 04:33:18 Terraform plan |       + producer_byte_rate   = 100000
 2024/12/09 04:33:18 Terraform plan |       + resource_instance_id = "crn:v1:bluemix:public:messagehub:us-south:a/26f737d77ed726547f77e08f865c5a26:794b9f0c-535e-4860-b317-4e0a70323a22::"
 2024/12/09 04:33:18 Terraform plan |     }
 2024/12/09 04:33:18 Terraform plan | 
 2024/12/09 04:33:18 Terraform plan |   # ibm_event_streams_quota.eventstreams_quotas["iam-ServiceId-00000000-2222-0000-0000-000000000000"] will be created
 2024/12/09 04:33:18 Terraform plan |   + resource "ibm_event_streams_quota" "eventstreams_quotas" {
 2024/12/09 04:33:18 Terraform plan |       + consumer_byte_rate   = 200000
 2024/12/09 04:33:18 Terraform plan |       + entity               = "iam-ServiceId-00000000-2222-0000-0000-000000000000"
 2024/12/09 04:33:18 Terraform plan |       + id                   = (known after apply)
 2024/12/09 04:33:18 Terraform plan |       + producer_byte_rate   = 100000
 2024/12/09 04:33:18 Terraform plan |       + resource_instance_id = "crn:v1:bluemix:public:messagehub:us-south:a/26f737d77ed726547f77e08f865c5a26:794b9f0c-535e-4860-b317-4e0a70323a22::"
 2024/12/09 04:33:18 Terraform plan |     }
 2024/12/09 04:33:18 Terraform plan | 
 2024/12/09 04:33:18 Terraform plan | Plan: 3 to add, 0 to change, 2 to destroy.
 2024/12/09 04:33:18 Command finished successfully.
 
 2024/12/09 04:33:18 [1m-----  Terraform SHOW  -----[21m[0m
```

Schematics move command:
```
> ibmcloud schematics workspace state mv --id us-south.workspace.delete-me-es.f3f7cf76 --source "ibm_event_streams_quota.eventstreams_quotas[1]" --destination 'ibm_event_streams_quota.eventstreams_quotas["iam-ServiceId-00000000-2222-0000-0000-000000000000"]'

 2024/12/09 04:50:27 [1m-----  Terraform Commands  -----[21m[0m
 
 2024/12/09 04:50:27 [34mStarting command: terraform1.6 state mv ibm_event_streams_quota.eventstreams_quotas[0] ibm_event_streams_quota.eventstreams_quotas["iam-ServiceId-00000000-1111-0000-0000-000000000000"][39m[0m
 2024/12/09 04:50:27 Starting command: terraform1.6 state mv ibm_event_streams_quota.eventstreams_quotas[0] ibm_event_streams_quota.eventstreams_quotas["iam-ServiceId-00000000-1111-0000-0000-000000000000"]
 2024/12/09 04:50:29 Terraform state | Move "ibm_event_streams_quota.eventstreams_quotas[0]" to "ibm_event_streams_quota.eventstreams_quotas[\"iam-ServiceId-00000000-1111-0000-0000-000000000000\"]"
 2024/12/09 04:50:30 Terraform state | Successfully moved 1 object(s).
 2024/12/09 04:50:30 Command finished successfully.

> ibmcloud schematics workspace state mv --id us-south.workspace.delete-me-es.f3f7cf76 --source "ibm_event_streams_quota.eventstreams_quotas[1]" --destination 'ibm_event_streams_quota.eventstreams_quotas["iam-ServiceId-00000000-2222-0000-0000-000000000000"]'

 2024/12/09 04:52:00 [34mStarting command: terraform1.6 state mv ibm_event_streams_quota.eventstreams_quotas[1] ibm_event_streams_quota.eventstreams_quotas["iam-ServiceId-00000000-2222-0000-0000-00000000000 [...]

2024-12-11 13:17 UTC, ocofaigh commented
/run pipeline

2024-12-11 13:17 UTC, ocofaigh approved these changes

2024-12-11 16:17 UTC, merged